ci(build): 修复 PyInstaller命令中的参数格式
- 在 Windows 和 Linux/macOS 平台上修正了 PyInstaller 命令中的参数格式
- 将 "-name" 参数改为 "--name"，以符合 PyInstaller 的正确参数格式

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -70,10 +70,10 @@ jobs:
         run: |
           case "$RUNNER_OS" in
             Windows)
-              pyinstaller --onefile -name McFileFetcher-${{ runner.os }} --upx-dir="upx-win" McFileFetcher.py || { echo "PyInstaller failed on Windows"; exit 1; }
+              pyinstaller --onefile --name McFileFetcher-${{ runner.os }} --upx-dir="upx-win" McFileFetcher.py || { echo "PyInstaller failed on Windows"; exit 1; }
               ;;
             Linux|macOS)
-              pyinstaller --onefile -name McFileFetcher-${{ runner.os }} McFileFetcher.py || { echo "PyInstaller failed on $RUNNER_OS"; exit 1; }
+              pyinstaller --onefile --name McFileFetcher-${{ runner.os }} McFileFetcher.py || { echo "PyInstaller failed on $RUNNER_OS"; exit 1; }
               ;;
           esac
 
